export const FETCH_EMPLOYEE_DATA_REQUEST = "FETCH_EMPLOYEE_DATA_REQUEST";
export const FETCH_EMPLOYEE_DATA_SUCCESS = "FETCH_EMPLOYEE_DATA_SUCCESS";
export const FETCH_EMPLOYEE_DATA_FAILURE = "FETCH_EMPLOYEE_DATA_FAILURE";

export const ADD_EMPLOYEE_DATA = "ADD_EMPLOYEE_DATA";
export const ADD_EMPLOYEE_DATA_SUCCESS = "ADD_EMPLOYEE_DATA_SUCCESS";
export const ADD_EMPLOYEE_DATA_FAILURE = "ADD_EMPLOYEE_DATA_FAILURE";

export const DELETE_EMPLOYEE_DATA = "DELETE_EMPLOYEE_DATA";
export const DELETE_EMPLOYEE_DATA_SUCCESS = "DELETE_EMPLOYEE_DATA_SUCCESS";
export const DELETE_EMPLOYEE_DATA_FAILURE = "DELETE_EMPLOYEE_DATA_FAILURE";
